name: Build and Test React Application

on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
        branches: [main]
    pull_request:
        branches: [main]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    react-app-workflow:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 18.x
              uses: actions/setup-node@v2
              with:
                  node-version: 18.x
            - name: npm ci
              run: npm ci
            - name: format
              run: npm run format
            - name: test
              run: npm run test
            - name: lint
              run: npm run lint
            # - name: build
            #  run: npm run build